version: '2'
services:
  db:
    image: postgres
    volumes:
      - postgresql-data:/var/lib/postgresql

  web:
    command: python manage.py runserver 0.0.0.0:8000
    build: .
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint: /usr/bin/wait-for-it.sh db:5432 --

volumes:
  postgresql-data:
    driver: local-persist
    driver_opts:
      mountpoint: /data/local-persist/postgresql
