version: '2'
services:
  db:
    image: postgres
    volumes:
      - postgresql-data:/var/lib/postgresql

  db_wait:
    image: postgres
    links: ["db"]
    command: >
      /bin/bash -c '
        until psql --host=db --username=postgres; do sleep 1; done;
        echo "Postgres is up"
      '

  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/config/redis.conf:/usr/local/etc/redis/redis.conf
      - /tmp/redis-data:/data
    ports:
      - "63790:6379"

  web:
    command: python manage.py runserver 0.0.0.0:8000
    build: .
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - db_wait
      - redis
    entrypoint:
      - /code/entrypoint.sh

volumes:
  postgresql-data:
    driver: local-persist
    driver_opts:
      mountpoint: /data/local-persist/postgresql
