version: '2'
services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
    ports:
      - "54320:5432"

  db_wait:
    image: postgres
    links:
      - db
    command: >
      /bin/bash -c '
        until psql --host=db --username=postgres; do sleep 1; done;
        echo "Postgres is up"
      '

  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/config/redis.conf:/usr/local/etc/redis/redis.conf
      - /tmp/redis-data:/data
    ports:
      - "63790:6379"

  web:
    command: python manage.py runserver 0.0.0.0:8000
    build: .
    volumes:
      - ./apps:/apps
    ports:
      - "8000:8000"
    depends_on:
      - db_wait
    links:
      - db
      - redis
